/**
 * Baseline translation file
 * Created: 22-May-2011 07:38 GMT
 */
exports.language = {
  "About You":"About You",
  "Add your keyword to the url to view other streams ... e.g.":"Add your keyword to the url to view other streams ... e.g.",
  "Admin":"Admin",
  "Args":"Args",
  "Arguments":"Arguments",
  "Author":"Author",
  "Breaking News":"Breaking News",
  "CRON Time":"CRON Time",
  "Categorisation":"Categorisation",
  "Click to create":"Click to create",
  "Content":"Content",
  "Content Type":"Content Type",
  "Content Types":"Content Types",
  "Could not save content because {msg}.":"Could not save content because {msg}.",
  "Could not save content type because {msg}.":"Could not save content type because {msg}.",
  "Could not save job because {msg}.":"Could not save job because {msg}.",
  "Could not update content because {msg}.":"Could not update content because {msg}.",
  "Could not update content type because {msg}.":"Could not update content type because {msg}.",
  "Could not update job because {msg}.":"Could not update job because {msg}.",
  "Create Content ...":"Create Content ...",
  "Create Content Type":"Create Content Type",
  "Create New Job":"Create New Job",
  "Date to appear as published.":"Date to appear as published.",
  "Date to be published (if scheduled).":"Date to be published (if scheduled).",
  "Delete Content":"Delete Content",
  "Delete Content Type":"Delete Content Type",
  "Delete Job":"Delete Job",
  "Description":"Description",
  "Disable All":"Disable All",
  "Double click to edit content block ...":"Double click to edit content block ...",
  "Edit Content":"Edit Content",
  "Edit Content ...":"Edit Content ...",
  "Edit Content Type":"Edit Content Type",
  "Edit Job":"Edit Job",
  "Edit Profile":"Edit Profile",
  "Email":"Email",
  "Enable All":"Enable All",
  "Enable or disable the job":"Enable or disable the job",
  "Enabled":"Enabled",
  "Enter a unique name for the job":"Enter a unique name for the job",
  "Enter comma delimited tags to help manage this content.":"Enter comma delimited tags to help manage this content.",
  "Enter some short text that describes the content, appears in lists.":"Enter some short text that describes the content, appears in lists.",
  "Enter the arguments (as per the job function)":"Enter the arguments (as per the job function)",
  "Enter the full content text.":"Enter the full content text.",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"Enter the menu heirarchy, e.g. \"welcome/about\"",
  "Is Public":"Is Public",
  "Jade Template":"Jade Template",
  "Job":"Job",
  "Job Function":"Job Function",
  "Job: ascsdcasdcasdcasdc":"Job: ascsdcasdcasdcasdc",
  "Language":"Language",
  "Languages":"Languages",
  "Last Updated":"Last Updated",
  "Layout":"Layout",
  "Log In":"Log In",
  "Login":"Login",
  "Method":"Method",
  "Module":"Module",
  "Name":"Name",
  "Navigation":"Navigation",
  "New Content":"New Content",
  "New Content Type":"New Content Type",
  "New Job":"New Job",
  "No jobs defined":"No jobs defined",
  "Password":"Password",
  "Permanent URL / Alias":"Permanent URL / Alias",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"Permanent url (no spaces or invalid html characters), if left blank is generated from title.",
  "Public":"Public",
  "Published":"Published",
  "Register":"Register",
  "Save Content":"Save Content",
  "Save Content Type":"Save Content Type",
  "Save Job":"Save Job",
  "Save Profile":"Save Profile",
  "Schedule":"Schedule",
  "Scheduled":"Scheduled",
  "Scheduled Jobs":"Scheduled Jobs",
  "Scheduler":"Scheduler",
  "Select the job function to run as per this schedule":"Select the job function to run as per this schedule",
  "Select the status (published is visible to all public).":"Select the status (published is visible to all public).",
  "Select the type, this impacts custom fields and page display.":"Select the type, this impacts custom fields and page display.",
  "Status":"Status",
  "Tag Cloud":"Tag Cloud",
  "Tags":"Tags",
  "Taxonomy":"Taxonomy",
  "Teaser":"Teaser",
  "Template":"Template",
  "The content has now been deleted.":"The content has now been deleted.",
  "The content type has now been deleted.":"The content type has now been deleted.",
  "Title":"Title",
  "Title to appear for this piece of content.":"Title to appear for this piece of content.",
  "Tweet Stream":"Tweet Stream",
  "Type":"Type",
  "Update Profile":"Update Profile",
  "Updated":"Updated",
  "User":"User",
  "Username":"Username",
  "You may have entered an incorrect username or password, please try again.":"You may have entered an incorrect username or password, please try again.",
  "You need to add a \"breaking\" tag to content to have it appear here.":"You need to add a \"breaking\" tag to content to have it appear here.",
  "for":"for",
  "{name} Profile":"{name} Profile",
}