/**
 * Baseline translation file
 * Created: 22-May-2011 07:38 GMT
 */
exports.language = {
  "About You":"About You",
  "Admin":"Admin",
  "Arguments":"Arguments",
  "CRON Time":"CRON Time",
  "Categorisation":"Categorisation",
  "Click to create":"Click to create",
  "Content":"Content",
  "ContentType":"ContentType",
  "Could not save content because {msg}.":"Could not save content because {msg}.",
  "Could not save content type because {msg}.":"Could not save content type because {msg}.",
  "Could not save job because {msg}.":"Could not save job because {msg}.",
  "Create Content ...":"Create Content ...",
  "Create Content Type":"Create Content Type",
  "Create New Job":"Create New Job",
  "Date to appear as published.":"Date to appear as published.",
  "Date to be published (if scheduled).":"Date to be published (if scheduled).",
  "Description":"Description",
  "Double click to edit content block ...":"Double click to edit content block ...",
  "Edit Content Type":"Edit Content Type",
  "Email":"Email",
  "Enable or disable the job":"Enable or disable the job",
  "Enabled":"Enabled",
  "Enter a unique name for the job":"Enter a unique name for the job",
  "Enter comma delimited tags to help manage this content.":"Enter comma delimited tags to help manage this content.",
  "Enter some short text that describes the content, appears in lists.":"Enter some short text that describes the content, appears in lists.",
  "Enter the arguments (as per the job function)":"Enter the arguments (as per the job function)",
  "Enter the full content text.":"Enter the full content text.",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"Enter the menu heirarchy, e.g. \"welcome/about\"",
  "Is Public":"Is Public",
  "Job Function":"Job Function",
  "Job: Github":"Job: Github",
  "Language":"Language",
  "Layout":"Layout",
  "Log In":"Log In",
  "Login":"Login",
  "Name":"Name",
  "Password":"Password",
  "Permanent URL / Alias":"Permanent URL / Alias",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"Permanent url (no spaces or invalid html characters), if left blank is generated from title.",
  "Published":"Published",
  "Register":"Register",
  "Save Content":"Save Content",
  "Save Content Type":"Save Content Type",
  "Save Job":"Save Job",
  "Save Profile":"Save Profile",
  "Scheduled":"Scheduled",
  "Select the job function to run as per this schedule":"Select the job function to run as per this schedule",
  "Select the status (published is visible to all public).":"Select the status (published is visible to all public).",
  "Select the type, this impacts custom fields and page display.":"Select the type, this impacts custom fields and page display.",
  "Status":"Status",
  "Tag Cloud":"Tag Cloud",
  "Tags":"Tags",
  "Taxonomy":"Taxonomy",
  "Teaser":"Teaser",
  "The content has now been deleted.":"The content has now been deleted.",
  "The content type has now been deleted.":"The content type has now been deleted.",
  "Title":"Title",
  "Title to appear for this piece of content.":"Title to appear for this piece of content.",
  "Type":"Type",
  "Update Profile":"Update Profile",
  "Username":"Username",
  "{name} Profile":"{name} Profile"
}