/**
 * Translation file for russian
 * Test file via Google Translate
 */
exports.language = {
  "About You":"О Вас",
  "Add your keyword to the url to view other streams ... e.g.":"Добавить ключевое слово в URL, чтобы просмотреть другие потоки ... например,",
  "Admin":"Admin",
  "Args":"Args",
  "Arguments":"Аргументы",
  "Author":"Автор",
  "Breaking News":"Главные новости",
  "CRON Time":"CRON время",
  "Categorisation":"Категоризация",
  "Click to create":"Нажмите, чтобы создать",
  "Content":"Содержание",
  "Content Type":"Тип содержимого",
  "Content Types":"Типы содержимого",
  "Could not save content because {msg}.":"Не удалось сохранить содержимое, поскольку {msg}.",
  "Could not save content type because {msg}.":"Не удалось сохранить тип содержимого, так как {msg}.",
  "Could not save job because {msg}.":"Не удалось сохранить работу, потому что {msg}.",
  "Could not update content because {msg}.":"Не удалось обновить содержание, так как {msg}.",
  "Could not update content type because {msg}.":"Не удалось обновить тип содержимого, так как {msg}.",
  "Could not update job because {msg}.":"Не удалось обновить работу, потому что {msg}.",
  "Create Content ...":"Создать материал ...",
  "Create Content Type":"Создание типов содержимого",
  "Create New Job":"Создать новую работу",
  "Date to appear as published.":"Дата выступать в качестве опубликованы.",
  "Date to be published (if scheduled).":"Дата будет опубликован (если предусмотрена).",
  "Delete Content":"Удалить содержание",
  "Delete Content Type":"Удалить типа содержимого",
  "Delete Job":"Удалить работы",
  "Description":"Описание",
  "Disable All":"Отключить все",
  "Double click to edit content block ...":"Двойной клик для редактирования содержимого блока ...",
  "Edit Content":"Изменить содержание",
  "Edit Content ...":"Редактировать содержимое ...",
  "Edit Content Type":"Изменение типа содержимого",
  "Edit Job":"Изменить работы",
  "Edit Profile":"Изменить профиль",
  "Email":"Электронная почта",
  "Enable All":"Включить все",
  "Enable or disable the job":"Включить или выключить работу",
  "Enabled":"Включено",
  "Enter a unique name for the job":"Введите уникальное имя для работы",
  "Enter comma delimited tags to help manage this content.":"Введите запятую теги, которые помогут справиться с этим содержанием.",
  "Enter some short text that describes the content, appears in lists.":"Введите какой-нибудь короткий текст, который описывает содержимое, появляется в списках.",
  "Enter the arguments (as per the job function)":"Введите аргументы (как в работе функции)",
  "Enter the full content text.":"Введите полный текст контента.",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"Введите иерархии меню, например, \"Добро пожаловать / О\"",
  "Is Public":"Является общественной",
  "Jade Template":"Джейд шаблона",
  "Job":"Работа",
  "Job Function":"Работа функции",
  "Job: ascsdcasdcasdcasdc":"Работа: ascsdcasdcasdcasdc",
  "Language":"Язык",
  "Languages":"Языки",
  "Last Updated":"Последнее обновление",
  "Layout":"Макет",
  "Log In":"Войти",
  "Login":"Войти",
  "Method":"Метод",
  "Module":"Модуль",
  "Name":"Название",
  "Navigation":"Навигация",
  "New Content":"Новое содержание",
  "New Content Type":"Новый тип содержимого",
  "New Job":"Новые работы",
  "No jobs defined":"Нет рабочих мест определены",
  "Password":"Пароль",
  "Permanent URL / Alias":"Постоянный URL / Alias",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"Постоянный URL (без пробелов или недействительным HTML символов), если оставить пустым генерируется из названия.",
  "Public":"Общественные",
  "Published":"Опубликовано",
  "Register":"Регистрация",
  "Save Content":"Сохранить содержимое",
  "Save Content Type":"Сохранить тип содержимого",
  "Save Job":"Сохранить работу",
  "Save Profile":"Сохранить профиль",
  "Schedule":"Расписание",
  "Scheduled":"Запланированные",
  "Scheduled Jobs":"Запланированные задания",
  "Scheduler":"Планировщик",
  "Select the job function to run as per this schedule":"Выберите задание функции для запуска в соответствии с этим графиком",
  "Select the status (published is visible to all public).":"Выберите статус (опубликовано видна все государственные).",
  "Select the type, this impacts custom fields and page display.":"Выберите тип, это воздействие настраиваемые поля и отображения страниц.",
  "Status":"Статус",
  "Tag Cloud":"Облако тегов",
  "Tags":"Теги",
  "Taxonomy":"Таксономия",
  "Teaser":"Задира",
  "Template":"Шаблон",
  "The content has now been deleted.":"Содержание теперь уже удален.",
  "The content type has now been deleted.":"Тип содержимого в настоящее время уже удален.",
  "Title":"Название",
  "Title to appear for this piece of content.":"Название явки в этой части содержимого.",
  "Tweet Stream":"Чирикать поток",
  "Type":"Тип",
  "Update Profile":"Обновление профиля",
  "Updated":"Обновлено",
  "User":"Пользователь",
  "Username":"Имя пользователя",
  "You may have entered an incorrect username or password, please try again.":"Возможно, вы ввели неверное имя пользователя или пароль, пожалуйста, попробуйте еще раз.",
  "You need to add a \"breaking\" tag to content to have it appear here.":"Вам необходимо добавить \"взлома\" теги к содержанию, чтобы он появится здесь.",
  "for":"для",
  "{name} Profile":"{name} профиля",
}