/**
 * Translation file for spanish (castillon) - TODO!
 * Test file via Google Translate
 */
exports.language = {
  "About You":"Acerca de Usted",
  "Add your keyword to the url to view other streams ... e.g.":"Añade tu palabra clave para la url para ver otras corrientes ... por ejemplo,",
  "Admin":"Admin",
  "Args":"Args",
  "Arguments":"Alegaciones",
  "Author":"Autor",
  "Breaking News":"Noticias de última hora",
  "CRON Time":"CRON Tiempo",
  "Categorisation":"Categorización",
  "Click to create":"Haga clic para crear",
  "Content":"Contenido",
  "Content Type":"Tipo de contenido",
  "Content Types":"Los tipos de contenido",
  "Could not save content because {msg}.":"No se pudo guardar el contenido, porque {msg}.",
  "Could not save content type because {msg}.":"No se pudo guardar el tipo de contenido porque {msg}.",
  "Could not save job because {msg}.":"No se pudo guardar oferta porque {msg}.",
  "Could not update content because {msg}.":"No se pudo actualizar el contenido, porque {msg}.",
  "Could not update content type because {msg}.":"No se pudo actualizar el tipo de contenido porque {msg}.",
  "Could not update job because {msg}.":"No se pudo actualizar trabajo porque {msg}.",
  "Create Content ...":"Crear contenido ...",
  "Create Content Type":"Crear Tipo de contenido",
  "Create New Job":"Crear nuevo trabajo",
  "Date to appear as published.":"Fecha que aparezca publicada.",
  "Date to be published (if scheduled).":"Fecha que se publicará (si programado).",
  "Delete Content":"Elimina el contenido",
  "Delete Content Type":"Tipo de contenido Eliminar",
  "Delete Job":"Eliminar Trabajo",
  "Description":"Descripción",
  "Disable All":"Deshabilitar todo",
  "Double click to edit content block ...":"Haga doble clic para editar el contenido del bloque ...",
  "Edit Content":"Editar contenido",
  "Edit Content ...":"Editar contenido ...",
  "Edit Content Type":"Editar Tipo de Contenido",
  "Edit Job":"Edición de trabajo",
  "Edit Profile":"Editar Perfil",
  "Email":"Correo electrónico",
  "Enable All":"Habilitar todos",
  "Enable or disable the job":"Activar o desactivar el Trabajo",
  "Enabled":"Habilitado",
  "Enter a unique name for the job":"Escriba un nombre único para el trabajo",
  "Enter comma delimited tags to help manage this content.":"Introduzca las etiquetas delimitado por comas para ayudar a manejar este contenido.",
  "Enter some short text that describes the content, appears in lists.":"Escriba un texto breve que describe el contenido, aparece en las listas.",
  "Enter the arguments (as per the job function)":"Introduzca los argumentos (de acuerdo con la función de trabajo)",
  "Enter the full content text.":"Introduzca el texto contenido completo.",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"Introduzca la jerarquía del menú, por ejemplo, \"Bienvenido / sobre\"",
  "Is Public":"Es público",
  "Jade Template":"Jade plantilla",
  "Job":"Empleo",
  "Job Function":"Función de trabajo",
  "Job: ascsdcasdcasdcasdc":"Trabajo: ascsdcasdcasdcasdc",
  "Language":"Idioma",
  "Languages":"Idiomas",
  "Last Updated":"Última actualización",
  "Layout":"Diseño",
  "Log In":"Entrar",
  "Login":"Iniciar sesión",
  "Method":"Método",
  "Module":"Módulo",
  "Name":"Nombre",
  "Navigation":"Navegación",
  "New Content":"Nuevo contenido",
  "New Content Type":"Nuevo tipo de contenido",
  "New Job":"Nuevo trabajo",
  "No jobs defined":"No hay puestos de trabajo definidos",
  "Password":"Contraseña",
  "Permanent URL / Alias":"URL Permanente / Alias",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"URL Permanente (sin espacios ni caracteres no válidos html), si se deja en blanco se genera a partir del título.",
  "Public":"Pública",
  "Published":"Publicado",
  "Register":"Registrarse",
  "Save Content":"Guardar contenido",
  "Save Content Type":"Guardar Tipo de contenido",
  "Save Job":"Guardar Trabajo",
  "Save Profile":"Guardar perfil",
  "Schedule":"Lista",
  "Scheduled":"Programado",
  "Scheduled Jobs":"Trabajos programados",
  "Scheduler":"Programador",
  "Select the job function to run as per this schedule":"Seleccione la función de trabajo a ejecutar de acuerdo con este calendario",
  "Select the status (published is visible to all public).":"Seleccione el estado (publicado es visible para todos los públicos).",
  "Select the type, this impacts custom fields and page display.":"Seleccione el tipo, estos campos efectos personalizados y visualización de la página.",
  "Status":"Condición Jurídica y Social",
  "Tag Cloud":"Nube de etiquetas",
  "Tags":"Etiquetas",
  "Taxonomy":"Taxonomía",
  "Teaser":"Teaser",
  "Template":"Plantilla",
  "The content has now been deleted.":"El contenido ha sido eliminado.",
  "The content type has now been deleted.":"El tipo de contenido se ha eliminado.",
  "Title":"Título",
  "Title to appear for this piece of content.":"Título que aparecerá para este elemento de contenido.",
  "Tweet Stream":"Tweet corriente",
  "Type":"Tipo",
  "Update Profile":"Actualizar perfil",
  "Updated":"Actualización",
  "User":"Usuario",
  "Username":"Nombre de usuario",
  "You may have entered an incorrect username or password, please try again.":"Es posible que haya introducido un nombre de usuario o contraseña incorrectos, por favor, inténtelo de nuevo.",
  "You need to add a \"breaking\" tag to content to have it appear here.":"Es necesario añadir una \"ruptura\" de etiquetas de contenido para que aparezca aquí.",
  "for":"de",
  "{name} Profile":"{name} Perfil",
}