/**
 * Translation file for spanish (castillon) - TODO!
 * Test file via Google Translate
 */
exports.language = {
  "About You":"Acerca de Usted",
  "Admin":"Admin",
  "Arguments":"Alegaciones",
  "CRON Time":"CRON Tiempo",
  "Categorisation":"Categorización",
  "Click to create":"Haga clic para crear",
  "Content":"Contenido",
  "ContentType":"ContentType",
  "Could not save content because {msg}.":"No se pudo guardar el contenido, porque {msg}.",
  "Could not save content type because {msg}.":"No se pudo guardar el tipo de contenido porque msg {}.",
  "Could not save job because {msg}.":"No se pudo guardar oferta porque msg {}.",
  "Create Content ...":"Crear contenido ...",
  "Create Content Type":"Crear Tipo de contenido",
  "Create New Job":"Crear nuevo trabajo",
  "Date to appear as published.":"Fecha que aparezca publicada.",
  "Date to be published (if scheduled).":"Fecha que se publicará (si programado).",
  "Description":"Descripción",
  "Double click to edit content block ...":"Haga doble clic para editar el contenido del bloque ...",
  "Edit Content Type":"Editar Tipo de Contenido",
  "Email":"Correo electrónico",
  "Enable or disable the job":"Activar o desactivar el Trabajo",
  "Enabled":"Habilitado",
  "Enter a unique name for the job":"Escriba un nombre único para el trabajo",
  "Enter comma delimited tags to help manage this content.":"Introduzca las etiquetas delimitado por comas para ayudar a manejar este contenido.",
  "Enter some short text that describes the content, appears in lists.":"Escriba un texto breve que describe el contenido, aparece en las listas.",
  "Enter the arguments (as per the job function)":"Introduzca los argumentos (de acuerdo con la función de trabajo)",
  "Enter the full content text.":"Introduzca el texto contenido completo.",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"Introduzca la jerarquía del menú, por ejemplo, \"Bienvenido / sobre\"",
  "Is Public":"Es público",
  "Job Function":"Función de trabajo",
  "Job: Github":"Trabajo: Github",
  "Language":"Idioma",
  "Layout":"Diseño",
  "Log In":"Entrar",
  "Login":"Iniciar sesión",
  "Name":"Nombre",
  "Password":"Contraseña",
  "Permanent URL / Alias":"URL Permanente / Alias",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"URL Permanente (sin espacios ni caracteres no válidos html), si se deja en blanco se genera a partir del título.",
  "Published":"Publicado",
  "Register":"Registrarse",
  "Save Content":"Guardar contenido",
  "Save Content Type":"Guardar Tipo de contenido",
  "Save Job":"Guardar Trabajo",
  "Save Profile":"Guardar perfil",
  "Scheduled":"Programado",
  "Select the job function to run as per this schedule":"Seleccione la función de trabajo a ejecutar de acuerdo con este calendario",
  "Select the status (published is visible to all public).":"Seleccione el estado (publicado es visible para todos los públicos).",
  "Select the type, this impacts custom fields and page display.":"Seleccione el tipo, estos campos efectos personalizados y visualización de la página.",
  "Status":"Condición Jurídica y Social",
  "Tag Cloud":"Nube de etiquetas",
  "Tags":"Etiquetas",
  "Taxonomy":"Taxonomía",
  "Teaser":"Teaser",
  "The content has now been deleted.":"El contenido ha sido eliminado.",
  "The content type has now been deleted.":"El tipo de contenido se ha eliminado.",
  "Title":"Título",
  "Title to appear for this piece of content.":"Título que aparecerá para este elemento de contenido.",
  "Type":"Tipo",
  "Update Profile":"Actualizar perfil",
  "Username":"Nombre de usuario",
  "{name} Profile":"{Nombre} Perfil",
}