/**
 * Translation file for japanese - TODO!
 * Test file via Google Translate
 */
exports.language = {
  "About You":"アバウトユー",
  "Admin":"管理者",
  "Arguments":"引数",
  "CRON Time":"のCRON時間",
  "Categorisation":"カテゴリー分類",
  "Click to create":"作成する場合にクリックします",
  "Content":"コンテンツ",
  "ContentType":"ContentTypeの",
  "Could not save content because {msg}.":"コンテンツを保存することができませんでしたので、{メッセージ}。",
  "Could not save content type because {msg}.":"ため、{メッセージ}コンテンツタイプを保存することができませんでした。",
  "Could not save job because {msg}.":"ジョブを保存することができませんでしたので、{メッセージ}。",
  "Create Content ...":"コンテンツの作成...",
  "Create Content Type":"コンテンツタイプを作成します。",
  "Create New Job":"新規ジョブの作成",
  "Date to appear as published.":"日付は、公開されて表示される。",
  "Date to be published (if scheduled).":"日付が（予定の場合）発行される。",
  "Description":"概要",
  "Double click to edit content block ...":"ダブルコンテンツブロックを編集するにはここをクリック...",
  "Edit Content Type":"コンテンツタイプを編集する",
  "Email":"Eメール",
  "Enable or disable the job":"を有効または無効にする仕事",
  "Enabled":"有効",
  "Enter a unique name for the job":"ジョブの一意の名前を入力してください",
  "Enter comma delimited tags to help manage this content.":"このコンテンツを管理するためのカンマ区切りのタグを入力してください。",
  "Enter some short text that describes the content, appears in lists.":"は、コンテンツを記述するリストに表示されるいくつかの短いテキストを入力します。",
  "Enter the arguments (as per the job function)":"（仕事関数ごとなど）の引数を入力します。",
  "Enter the full content text.":"完全なコンテンツのテキストを入力します。",
  "Enter the menu heirarchy, e.g. \"welcome/about\"":"\"歓迎/約\"など、メニューの階層を入力してください",
  "Is Public":"されているパブリック",
  "Job Function":"ジョブ機能",
  "Job: Github":"職業：ギットハブ",
  "Language":"言語",
  "Layout":"レイアウト",
  "Log In":"ログイン",
  "Login":"ログイン",
  "Name":"名",
  "Password":"パスワード",
  "Permanent URL / Alias":"永久のURL /エイリアス",
  "Permanent url (no spaces or invalid html characters), if left blank is generated from title.":"空欄の場合永久urlは（ただし、空白または無効なHTML文字）、タイトルから生成されます。",
  "Published":"公開",
  "Register":"レジスタ",
  "Save Content":"保存コンテンツ",
  "Save Content Type":"コンテンツタイプを保存",
  "Save Job":"保存ジョブ",
  "Save Profile":"[プロファイルの保存",
  "Scheduled":"スケジュール",
  "Select the job function to run as per this schedule":"このスケジュールに従って実行するジョブ機能を選択します。",
  "Select the status (published is visible to all public).":"ステータス（すべてのパブリックに表示されて公開されて）を選択します。",
  "Select the type, this impacts custom fields and page display.":"タイプは、この影響カスタムフィールドとページの表示を選択してください。",
  "Status":"ステータス",
  "Tag Cloud":"タグクラウド",
  "Tags":"タグ",
  "Taxonomy":"分類",
  "Teaser":"難問",
  "The content has now been deleted.":"コンテンツは現在削除されています。",
  "The content type has now been deleted.":"コンテンツタイプは、現在削除されています。",
  "Title":"タイトル",
  "Title to appear for this piece of content.":"タイトルは、コンテンツのこの部分に表示される。",
  "Type":"タイプ",
  "Update Profile":"プロフィールを更新",
  "Username":"ユーザー名",
  "{name} Profile":"{name}のプロフィール",
}